package xaut.wjh.entity;
// Generated 2018-4-18 20:02:14 by Hibernate Tools 5.2.8.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TBooks generated by hbm2java
 */
@Entity
@Table(name = "t_books", catalog = "book_db")
public class TBooks implements java.io.Serializable {

	private static final long serialVersionUID = 8758998813592459755L;
	private Integer id;
	private String name;
	private Float price;
	private String auth;
	private String img;
	private BigDecimal rebate;
	private Integer stock;
	private String publisher;
	private Date publishdate;
	private Integer pages;
	private String size;
	private Integer printtimes;
	private Integer versions;
	private String brief;
	private String content;
	private Date onlinetime;
	private Set<TTypes> TTypeses = new HashSet<TTypes>(0);

	public TBooks() {
	}

	public TBooks(String name, Float price, String auth, String img, BigDecimal rebate, Integer stock, String publisher,
			Date publishdate, Integer pages, String size, Integer printtimes, Integer versions, String brief,
			String content, Date onlinetime, Set<TTypes> TTypeses) {
		this.name = name;
		this.price = price;
		this.auth = auth;
		this.img = img;
		this.rebate = rebate;
		this.stock = stock;
		this.publisher = publisher;
		this.publishdate = publishdate;
		this.pages = pages;
		this.size = size;
		this.printtimes = printtimes;
		this.versions = versions;
		this.brief = brief;
		this.content = content;
		this.onlinetime = onlinetime;
		this.TTypeses = TTypeses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NAME", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "price", precision = 12, scale = 0)
	public Float getPrice() {
		return this.price;
	}

	public void setPrice(Float price) {
		this.price = price;
	}

	@Column(name = "auth", length = 30)
	public String getAuth() {
		return this.auth;
	}

	public void setAuth(String auth) {
		this.auth = auth;
	}

	@Column(name = "img", length = 40)
	public String getImg() {
		return this.img;
	}

	public void setImg(String img) {
		this.img = img;
	}

	@Column(name = "rebate", precision = 3)
	public BigDecimal getRebate() {
		return this.rebate;
	}

	public void setRebate(BigDecimal rebate) {
		this.rebate = rebate;
	}

	@Column(name = "stock")
	public Integer getStock() {
		return this.stock;
	}

	public void setStock(Integer stock) {
		this.stock = stock;
	}

	@Column(name = "publisher", length = 50)
	public String getPublisher() {
		return this.publisher;
	}

	public void setPublisher(String publisher) {
		this.publisher = publisher;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "publishdate", length = 10)
	public Date getPublishdate() {
		return this.publishdate;
	}

	public void setPublishdate(Date publishdate) {
		this.publishdate = publishdate;
	}

	@Column(name = "pages")
	public Integer getPages() {
		return this.pages;
	}

	public void setPages(Integer pages) {
		this.pages = pages;
	}

	@Column(name = "size", length = 10)
	public String getSize() {
		return this.size;
	}

	public void setSize(String size) {
		this.size = size;
	}

	@Column(name = "printtimes")
	public Integer getPrinttimes() {
		return this.printtimes;
	}

	public void setPrinttimes(Integer printtimes) {
		this.printtimes = printtimes;
	}

	@Column(name = "versions")
	public Integer getVersions() {
		return this.versions;
	}

	public void setVersions(Integer versions) {
		this.versions = versions;
	}

	@Column(name = "brief", length = 65535)
	public String getBrief() {
		return this.brief;
	}

	public void setBrief(String brief) {
		this.brief = brief;
	}

	@Column(name = "content", length = 4000)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "onlinetime", length = 10)
	public Date getOnlinetime() {
		return this.onlinetime;
	}

	public void setOnlinetime(Date onlinetime) {
		this.onlinetime = onlinetime;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "t_booktype", catalog = "book_db", joinColumns = {
			@JoinColumn(name = "bookId", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "typeId", nullable = false, updatable = false) })
	public Set<TTypes> getTTypeses() {
		return this.TTypeses;
	}

	public void setTTypeses(Set<TTypes> TTypeses) {
		this.TTypeses = TTypeses;
	}

	@Override
	public String toString() {
		return "TBooks [id=" + id + ", name=" + name + ", auth=" + auth + ", publisher=" + publisher + ", versions="
				+ versions + ", TTypeses=" + TTypeses + "]";
	}
	
	

}
