package xaut.wjh.entity;
// Generated 2018-4-17 1:01:21 by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TRoles generated by hbm2java
 */
@Entity
@Table(name = "t_roles", catalog = "book_db")
public class TRoles implements java.io.Serializable {

	private static final long serialVersionUID = -7694129373096832197L;
	private Integer id;
	private String rolename;
	private Set<TUsers> TUserses = new HashSet<TUsers>(0);

	public TRoles() {
	}

	public TRoles(String rolename, Set<TUsers> TUserses) {
		this.rolename = rolename;
		this.TUserses = TUserses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "rolename", length = 20)
	public String getRolename() {
		return this.rolename;
	}

	public void setRolename(String rolename) {
		this.rolename = rolename;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TRoles")
	public Set<TUsers> getTUserses() {
		return this.TUserses;
	}

	public void setTUserses(Set<TUsers> TUserses) {
		this.TUserses = TUserses;
	}

}
