package xaut.wjh.entity;
// Generated 2018-4-18 20:02:14 by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * TTypes generated by hbm2java
 */
@Entity
@Table(name = "t_types", catalog = "book_db")
public class TTypes implements java.io.Serializable {

	private static final long serialVersionUID = 586345718264030349L;
	private Integer id;
	private String name;
	private String descr;
	private Set<TBooks> TBookses = new HashSet<TBooks>(0);

	public TTypes() {
	}

	public TTypes(String name, String descr, Set<TBooks> TBookses) {
		this.name = name;
		this.descr = descr;
		this.TBookses = TBookses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NAME", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "descr", length = 50)
	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "t_booktype", catalog = "book_db", joinColumns = {
			@JoinColumn(name = "typeId", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "bookId", nullable = false, updatable = false) })
	public Set<TBooks> getTBookses() {
		return this.TBookses;
	}

	public void setTBookses(Set<TBooks> TBookses) {
		this.TBookses = TBookses;
	}

}
