package xaut.wjh.entity;
// Generated 2018-4-17 1:01:21 by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TUsers generated by hbm2java
 */
@Entity
@Table(name = "t_users", catalog = "book_db", uniqueConstraints = @UniqueConstraint(columnNames = "username"))
public class TUsers implements java.io.Serializable {

	private static final long serialVersionUID = 1510275937150159818L;
	private Integer id;
	private TRoles TRoles;
	private String username;
	private String password;
	private String photoName;
	private Boolean sex;
	private Integer age;
	private String phone;

	public TUsers() {
	}

	public TUsers(TRoles TRoles, String password) {
		this.TRoles = TRoles;
		this.password = password;
	}

	public TUsers(TRoles TRoles, String username, String password, String photoName, Boolean sex, Integer age,
			String phone) {
		this.TRoles = TRoles;
		this.username = username;
		this.password = password;
		this.photoName = photoName;
		this.sex = sex;
		this.age = age;
		this.phone = phone;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "roleId", nullable = false)
	public TRoles getTRoles() {
		return this.TRoles;
	}

	public void setTRoles(TRoles TRoles) {
		this.TRoles = TRoles;
	}

	@Column(name = "username", unique = true, length = 20)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 16)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "photoName", length = 150)
	public String getPhotoName() {
		return this.photoName;
	}

	public void setPhotoName(String photoName) {
		this.photoName = photoName;
	}

	@Column(name = "sex")
	public Boolean getSex() {
		return this.sex;
	}

	public void setSex(Boolean sex) {
		this.sex = sex;
	}

	@Column(name = "age")
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@Column(name = "phone", length = 15)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Override
	public String toString() {
		return "TUsers [id=" + id + ", TRoles=" + TRoles + ", username=" + username + ", password=" + password
				+ ", photoName=" + photoName + ", sex=" + sex + ", age=" + age + ", phone=" + phone + "]";
	}
	
	
	
	

}
